-- Enable PostGIS extension to use GEOGRAPHY type
CREATE EXTENSION IF NOT EXISTS postgis;

-- SQL script to set up the database schema for Strolldiary
-- Table containing user information
CREATE TABLE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Table containing information about all places available
CREATE TABLE IF NOT EXISTS itinerary_places (
  place_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_name VARCHAR(128) NOT NULL,
  description TEXT,
  coordinates GEOGRAPHY(Point, 4326) NOT NULL, -- Using PostGIS for geographic data
  address VARCHAR(256) NOT NULL
);


-- Table of trip details (title, description, owner)
CREATE TABLE IF NOT EXISTS itineraries (
  itin_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INT NOT NULL REFERENCES users(user_id),
  title VARCHAR(128) NOT NULL,
  description TEXT,
  num_travelers INT NOT NULL,
  start_day DATE,
  end_day DATE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Table of each day in the itinerary
CREATE TABLE IF NOT EXISTS itinerary_days (
  day_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itin_id INT NOT NULL REFERENCES itineraries(itin_id),
  day DATE NOT NULL,
  notes TEXT
);

-- Table containing booking information (planes, hotels, trains, etc.)
CREATE TABLE IF NOT EXISTS bookings (
  booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itin_id INT REFERENCES itineraries(itin_id) NOT NULL,
  booking_type VARCHAR(64) NOT NULL,
  provider VARCHAR(128),
  reference_code VARCHAR(128),
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Table containing expense details for budgeting for each trip
CREATE TABLE IF NOT EXISTS expenses (
  expenses_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itin_id INT NOT NULL REFERENCES itineraries(itin_id),
  budget DECIMAL(10, 2),
  current_spending DECIMAL(10, 2),
  current_spending_split DECIMAL (10, 2),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Table containing collaborators for each trip
CREATE TABLE IF NOT EXISTS collaborators (
  user_id INT NOT NULL REFERENCES users(user_id),
  itin_id INT NOT NULL REFERENCES itineraries(itin_id),
  role VARCHAR(16), -- 'viewer', 'editor', 'admin'
  PRIMARY KEY(user_id, itin_id)
);

-- Table containing itinerary entries and details (activity, travel, booking, etc.)
CREATE TABLE IF NOT EXISTS itinerary_entries (
  entry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itin_id INT NOT NULL REFERENCES itineraries(itin_id),
  day_id INT NOT NULL REFERENCES itinerary_days(day_id),
  entry_type VARCHAR(32) NOT NULL, -- 'activity', 'travel', etc.
  entry_ref_id INT NULL,       -- references activity/travel/booking row id
  order_in_day INT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Table containing the information for each of the itinerary items
CREATE TABLE IF NOT EXISTS itinerary_items (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id INT REFERENCES itinerary_places(place_id),
  name VARCHAR(128) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- Table containing travel information for each itinerary entry (flights, walks, public transite, etc.)
CREATE TABLE IF NOT EXISTS itinerary_travels (
  travel_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_place_id INT REFERENCES itinerary_places(place_id),
  to_place_id INT REFERENCES itinerary_places(place_id),
  travel_mode VARCHAR(32) NOT NULL,
  departure_time TIMESTAMPTZ,
  arrival_time TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- Table containing expense item informadocker exec -it strolldiary-postgres-1 psql -U postgres -d strolldiarydbtion like cost and description
CREATE TABLE IF NOT EXISTS expense_items (
  expense_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expenses_id INT NOT NULL REFERENCES expenses(expenses_id),
  expense_name VARCHAR(128) NOT NULL,
  cost DECIMAL(10, 2) NOT NULL
);

ALTER TABLE itinerary_days ADD CONSTRAINT fk_itinerary_days_itin_id 
FOREIGN KEY (itin_id) REFERENCES itineraries(itin_id);